### ISSUE TITLE
Smith Chart Component

### ISSUE THREAD

**Issue by dvcorreia** [drom/smith-chart#4]
The is any way of render the chart as a component ? Something like this:
```js
import React, { Component, Fragment } from 'react'
import ReactDOM from 'react-dom'
const genSmithChart = require('smith-chart')

export default class SmithChart2 extends Component{
    componentDidMount(){
        ReactDOM.render(
            genSmithChart(React.createElement)({ r: 512 }),
            document.getElementById('smithchartid')
        )
    }

    render(){
        return(
            <div id="smithchartid"></div>
        )
    }
}
```

**Comment by drom** [comment]
In current implementation of the library returns an closure function https://github.com/drom/smith-chart/blob/master/index.js#L121 :

```js
const genSmithChart = require('smith-chart');
```

Being called with your favorite `.createElement` implementation it will return collection (Object) of components and supporting data sets that you are free to customize and combine.

```js
const SC = genSmithChart(React.createElement);
```
Here is usage example: https://github.com/drom/smith-chart/blob/master/src/app.js#L40

I am not the big expert in JSX but you can probably rewrite it like this:

```jsx
<g transform={`translate(${ size - margin.left },${ size / 2 })`}>
    <SC.Grid.Re r={r} lines={SC.grid} />
    <SC.Grid.Im r={r}, lines={SC.grid} />
    <SC.ReLabels r={r} lines={SC.reLabels0} />
    <SC.Shape
        r={r}
        data={data}
        className="trace"
        x={e => e[0]}
        y={e => e[1]} />
</g>
```

`SC.grid` - https://github.com/drom/smith-chart/blob/master/index.js#L7 is just example of the typical grid but you might like different grid.

`SC.reLabels0` - https://github.com/drom/smith-chart/blob/master/index.js#L17 is set of convinient labels.
